spring:
  application:
    name: exercise-reservation-system
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3309/exercise_reservation
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
